type: array
items:
    oneOf:
        - type: array
          items:
              type: number
          minItems: 3
          maxItems: 4
        - type: object
          properties:
              red:
                  type: number
              green:
                  type: number
              blue:
                  type: number
              white:
                  type: number
          required:
              - red
              - green
              - blue
          additionalProperties: false

